/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/Leafs.glb --transform --keepmeshes -types 
Files: ./public/Leafs.glb [12.14MB] > C:\Users\Work\Desktop\psx-postprocess\Leafs-transformed.glb [149.96KB] (99%)
*/

import * as THREE from 'three'
import React from 'react'
import { Html, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Leaf: THREE.Mesh
    Screen_Center: THREE.Mesh
    Screen_Left: THREE.Mesh
    Screen_Right: THREE.Mesh
    Monitors: THREE.Mesh
  }
  materials: {
    Default: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Leafs-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Leaf.geometry} position={[0.017, 1.764, -0.59]} rotation={[-Math.PI, 0, 0]} scale={0.876} >
        <meshBasicMaterial map={materials.Default.map} side={THREE.DoubleSide} transparent={true}  alphaTest={0.65}  />
      </mesh>
      <mesh geometry={nodes.Monitors.geometry} position={[0, 0.326, -1.126]} rotation={[-2.82, -1.284, -2.911]} scale={[0.233, 0.554, 0.543]} >
        <meshBasicMaterial map={materials.Default.map} side={THREE.FrontSide}  />
      </mesh>
      <mesh position={[0.35, 0.86, 1.02]} rotation={[-0.055, Math.PI / 2, 0]} scale={[0.086,0.09,0.1]} >
        <Html style={{backgroundColor: 'yellow',}} transform occlude='blending'>
          <div style={{width: '430px', height: '320px'}}>
          </div>
        </Html>
      </mesh>
      <mesh position={[0.4, 0.76, 0.01]} rotation={[0, Math.PI / 2, -0.01]} scale={[0.086,0.09,0.1]} >
        <Html style={{backgroundColor: 'yellow',}} transform occlude='blending'>
          <iframe width="430" height="320" 
          src="https://www.youtube.com/embed/1400fzt0SHU?si=Z5N-oi9hO4EBgSKM&amp;controls=0&amp;loop=1&amp;autoplay=1&amp;mute=1"
          title="YouTube video player" 
          frameBorder="0" 
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
          referrerPolicy="strict-origin-when-cross-origin" 
          allowFullScreen ></iframe>
        </Html>
      </mesh>
      <mesh position={[0.36, 0.905, -0.99]} rotation={[2.975, Math.PI / 2+0.25, -2.911]} scale={[0.086,0.09,0.1]} >
        <Html style={{backgroundColor: 'yellow',}} transform occlude='blending'>
          <div style={{width: '430px', height: '320px'}}>
          </div>
        </Html>
      </mesh>

     </group>
  )
}

useGLTF.preload('/Leafs-transformed.glb')
