/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/Scene_Full.glb --transform --types 
Files: ./public/Scene_Full.glb [7.98MB] > C:\Users\Work\Desktop\psx-postprocess\Scene_Full-transformed.glb [150.18KB] (98%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Transparent: THREE.Mesh
    Standard: THREE.Mesh
  }
  materials: {}
}

export function House_Full(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Scene_Full-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Transparent.geometry} material={nodes.Transparent.material} rotation={[Math.PI / 2, 0, 0]} scale={0.01} >
        <meshStandardMaterial 
          map={(nodes.Transparent.material as THREE.MeshStandardMaterial).map} 
          side={THREE.DoubleSide} 
          alphaTest={0.96} 
        />
      </mesh>
      <mesh geometry={nodes.Standard.geometry} material={nodes.Standard.material} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/Scene_Full-transformed.glb')
